#!/bin/sh

# Copyright (C) 2017 Victor Kulichenko

# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation,  either version 3 of the License,  or (at your  option) any later
# version.

# This program is distributed in the  hope that it will be useful,  but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.

# You should have received a copy of  the GNU General Public License  along with
# this program. If not, see http://www.gnu.org/licenses/.

# Purpose:
# The script finds hardlinks to regular files within specified filesystem subtrees
# by finding all the files under them and grouping filenames by inode.

# Usage:
# harlinks [path [path ...]]

# Output format:
# <inode1><10 space chars><relative path to filename>
# <inode1><10 space chars><relative path to filename>

# <inode2><10 space chars><relative path to filename>
#  ...

find "$@" -type f -links +1 -printf "%i          %p\n" | sort -s -n -k 1,1 | uniq --group -w 10 | awk 'BEGIN{FS="\n";RS="";ORS="\n\n"}NF>1{print}'
